[project]
name = "capstone"
version = "0.1.0"
description = "Capstone project for AI/ML course"
readme = "README.md"
authors = [
    { name = "Mark Simms", email = "masimms@outlook.com" }
]
requires-python = ">=3.13,<3.14"

# Baseline (common) dependency set
dependencies = [ 
    "fastapi>=0.141.1",
    "gitpython>=3.1.59",
    "joblib>=1.4.2",
    "pandas>=3.0.5",
    "psutil>=6.0.0",
    "pydantic>=2.13.4",
    "scikit-learn>=1.9.0",
    "setuptools>=83.0.0",
    "tokenizers>=0.23.1",
    "typer>=0.27.0",
    "uvicorn>=0.52.0",
    
]

[project.optional-dependencies]
serving = [
    "tensorflow==2.21.0",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
find-links = ["./dependencies/wheels"]
environments = ["sys_platform == 'linux'", "sys_platform == 'darwin'"]
prerelease-package = { tensorflow = "allow" }

# Training loads by default; serving is for docker builds
conflicts = [ 
    [
        {group = "training"},
        {extra = "serving"}
    ]
]

default-groups = ["dev", "training"]

# Configure pytest options
[tool.pytest.ini_options]
markers = [
    "train: marks slow training tests",
]
filterwarnings = [
    "ignore:__array__ implementation doesn't accept a copy keyword:DeprecationWarning",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

# Additional packages for training
training = [ 
    "tensorflow==2.22.0.dev0+selfbuilt ; sys_platform == 'linux'",
    "ipykernel>=7.3.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "kagglehub>=1.0.2",
    "keras-tuner>=1.4.8",
    "seaborn>=0.13.2",
    "tensorboard>=2.21.0",
]
# Load testing
loadtest = [ 
    "locust>=2.32.0"
]